#### 写出导入pandas的语句，并且给pandas别名为`pd`。

In [23]:
import pandas as pd

#### 创建一个叫`name`的Series，里面包含字符串元素 `"小陈", "小李", "小王", "小张", "小赵", "小周"`，标签为`"001", "002", "003", "004", "005", "006"`。
#### 创建一个叫`gender`的Series，里面包含字符串元素 `"女", "女", "男", "男", "女", "男"`，标签为`"006", "005", "004", "003", "002", "001"`。
#### 创建一个叫`height`的Series，里面包含浮点数元素 `172.5, 168.0, 178.2, 181.3, 161.7`，标签为`"001", "002", "003", "004", "005"`。

In [24]:
name = pd.Series(["小陈", "小李", "小王", "小张", "小赵", "小周"],index=["001", "002", "003","004", "005", "006"])
gender = pd.Series(["女", "女", "男", "男", "女", "男"],index=["006", "005", "004", "003","002", "001"])
height = pd.Series([172.5, 168.0, 178.2, 181.3, 161.7],index=["001", "002", "003", "004","005"])
print(name)
print(gender)
print(height)

001    小陈
002    小李
003    小王
004    小张
005    小赵
006    小周
dtype: object
006    女
005    女
004    男
003    男
002    女
001    男
dtype: object
001    172.5
002    168.0
003    178.2
004    181.3
005    161.7
dtype: float64

#### 创建一个叫`students`的DataFrame，包含列名姓名、性别、身高，数据分别对应创建好的`name`、`gender`、以及`height`这三个Series。输出创建好的`students`。

In [25]:
students = pd.DataFrame({
    '姓名' : name,
    '性别' : gender.sort_index(),
    '身高' : height},
    index=["001", "002", "003","004", "005", "006"])
students

     姓名 性别     身高
001  小陈  男  172.5
002  小李  女  168.0
003  小王  男  178.2
004  小张  男  181.3
005  小赵  女  161.7
006  小周  女    NaN

#### 打印`students`所有索引和列名。

In [26]:
students.columns

Index(['姓名', '性别', '身高'], dtype='object')

In [27]:
students.index

Index(['001', '002', '003', '004', '005', '006'], dtype='object')

#### 通过`head`方法，输出`students`前五行数据。

In [28]:
students.head(5)

     姓名 性别     身高
001  小陈  男  172.5
002  小李  女  168.0
003  小王  男  178.2
004  小张  男  181.3
005  小赵  女  161.7

#### 输出把`students`的行和列进行转置后的结果。

In [29]:
students.T

      001    002    003    004    005  006
姓名     小陈     小李     小王     小张     小赵   小周
性别      男      女      男      男      女    女
身高  172.5  168.0  178.2  181.3  161.7  NaN

#### 输出`students`的身高列。

In [30]:
students['身高']

001    172.5
002    168.0
003    178.2
004    181.3
005    161.7
006      NaN
Name: 身高, dtype: float64

#### 输出`students`的性别和身高列。

In [33]:
students[['性别','身高']]

    性别     身高
001  男  172.5
002  女  168.0
003  男  178.2
004  男  181.3
005  女  161.7
006  女    NaN

#### 输出`students`索引为003的行。

In [36]:
students.loc['003']

姓名       小王
性别        男
身高    178.2
Name: 003, dtype: object

#### 输出`students`索引为003、004、005的行。

In [37]:
students.loc[['003','004','005']]

     姓名 性别     身高
003  小王  男  178.2
004  小张  男  181.3
005  小赵  女  161.7

#### 输出`students`里索引为005的身高。

In [38]:
students.loc['005']['身高']

np.float64(161.7)

#### 输出`students`索引为003、005的数据的姓名和身高。

In [39]:
students.loc[['003','005']][['姓名','身高']]

     姓名     身高
003  小王  178.2
005  小赵  161.7

#### 输出`students`索引为003、005的数据的所有变量。

In [40]:
students.loc[['003','005']]

     姓名 性别     身高
003  小王  男  178.2
005  小赵  女  161.7

#### 输出`students`里身高大于165的女性。

In [48]:
students[(students['性别']=='女')&(students['身高']>165)]

     姓名 性别     身高
002  小李  女  168.0