#### 写出导入pandas的语句，并且给pandas别名为`pd`。

In [124]:
import pandas as pd
import numpy as np

#### 创建一个名为`students`的DataFrame，包含数据如下：
```{"001": {"姓名": "小陈", "考试1": 85, "考试2": 95, "考试3": 92},
 "002": {"姓名": "小李", "考试1": 91, "考试2": 92, "考试3": 94},
 "003": {"姓名": "小王", "考试1": 86, "考试2": 81, "考试3": 89},
 "004": {"姓名": "小张", "考试1": 79, "考试2": 89, "考试3": 95},
 "005": {"姓名": "小赵", "考试1": 96, "考试2": 91, "考试3": 91},
 "006": {"姓名": "小周", "考试1": 81, "考试2": 89, "考试3": 92}
 }```
 
 #### 要求索引为学号（001、002等），列名为姓名、考试1、考试2、考试3，并输出创建好的DataFrame。

In [125]:
dic = {"001": {"姓名": "小陈", "考试1": 85, "考试2": 95, "考试3": 92},
 "002": {"姓名": "小李", "考试1": 91, "考试2": 92, "考试3": 94},
 "003": {"姓名": "小王", "考试1": 86, "考试2": 81, "考试3": 89},
 "004": {"姓名": "小张", "考试1": 79, "考试2": 89, "考试3": 95},
 "005": {"姓名": "小赵", "考试1": 96, "考试2": 91, "考试3": 91},
 "006": {"姓名": "小周", "考试1": 81, "考试2": 89, "考试3": 92}}
students = pd.DataFrame(dic)
students

    001 002 003 004 005 006
姓名   小陈  小李  小王  小张  小赵  小周
考试1  85  91  86  79  96  81
考试2  95  92  81  89  91  89
考试3  92  94  89  95  91  92

In [126]:
students = students.T
students
# students.insert(loc=1,column='年龄',value = [19,19,19,19,19,19],allow_duplicates=True)
# students

     姓名 考试1 考试2 考试3
001  小陈  85  95  92
002  小李  91  92  94
003  小王  86  81  89
004  小张  79  89  95
005  小赵  96  91  91
006  小周  81  89  92

#### 给`students`增加一列`考试4`，数据依次为：`[72, 69, 79, 83, 82, 76]`。

In [127]:
students['考试4'] = [72, 69, 79, 83, 82, 76]
students

     姓名 考试1 考试2 考试3  考试4
001  小陈  85  95  92   72
002  小李  91  92  94   69
003  小王  86  81  89   79
004  小张  79  89  95   83
005  小赵  96  91  91   82
006  小周  81  89  92   76

#### 给`students`添加一行，索引为007，数据为：`"小杨", 79, 82, 81, 69`。

In [128]:
students.loc['007'] = ["小杨", 79, 82, 81, 69]
students

     姓名 考试1 考试2 考试3  考试4
001  小陈  85  95  92   72
002  小李  91  92  94   69
003  小王  86  81  89   79
004  小张  79  89  95   83
005  小赵  96  91  91   82
006  小周  81  89  92   76
007  小杨  79  82  81   69

#### 输出`students`删除索引为006、007的结果，但不要改变`students`本身。

In [129]:
students.drop(index=['006','007'],inplace=False)

     姓名 考试1 考试2 考试3  考试4
001  小陈  85  95  92   72
002  小李  91  92  94   69
003  小王  86  81  89   79
004  小张  79  89  95   83
005  小赵  96  91  91   82

In [130]:
students

     姓名 考试1 考试2 考试3  考试4
001  小陈  85  95  92   72
002  小李  91  92  94   69
003  小王  86  81  89   79
004  小张  79  89  95   83
005  小赵  96  91  91   82
006  小周  81  89  92   76
007  小杨  79  82  81   69

#### 输出`students`删除列名为“考试2”、“考试4”的结果，但不要改变`students`本身。

In [131]:
students.drop(columns=['考试2','考试4'],inplace=False)

     姓名 考试1 考试3
001  小陈  85  92
002  小李  91  94
003  小王  86  89
004  小张  79  95
005  小赵  96  91
006  小周  81  92
007  小杨  79  81

In [132]:
students

     姓名 考试1 考试2 考试3  考试4
001  小陈  85  95  92   72
002  小李  91  92  94   69
003  小王  86  81  89   79
004  小张  79  89  95   83
005  小赵  96  91  91   82
006  小周  81  89  92   76
007  小杨  79  82  81   69

#### 创建一个Series`bonus`，包含的值和值对应的索引分别为：`{"考试1": 2, "考试2": 3, "考试3": 2, "考试4": 5}`。输出这个Series与`students`里所有分数列相加后的结果，但不用更新`students`。

In [133]:
bonus_dic = {"考试1": 2, "考试2": 3, "考试3": 2, "考试4": 5}
ser = pd.Series(bonus_dic)
exam = ['考试1','考试2','考试3']
result = students[exam] + ser[exam].values
result

    考试1 考试2 考试3
001  87  98  94
002  93  95  96
003  88  84  91
004  81  92  97
005  98  94  93
006  83  92  94
007  81  85  83

#### 更新`students`的`考试4`，让每项数据值增加10，并输出更新后的结果。

In [134]:
students['考试4'] = students['考试4'] + 10
students

     姓名 考试1 考试2 考试3  考试4
001  小陈  85  95  92   82
002  小李  91  92  94   79
003  小王  86  81  89   89
004  小张  79  89  95   93
005  小赵  96  91  91   92
006  小周  81  89  92   86
007  小杨  79  82  81   79

#### 创建一个叫`student_average`的DataFrame，索引为学号，包含姓名列（列名为“姓名”），以及计算出三次考试平均值后的结果列（列名为“平均分”）。

In [135]:
average_score = students[exam].mean(axis=1)
average_score

student_average = pd.DataFrame({
    '姓名' : students['姓名'],
    '平均分' : average_score}
)
student_average

     姓名        平均分
001  小陈  90.666667
002  小李  92.333333
003  小王  85.333333
004  小张  87.666667
005  小赵  92.666667
006  小周  87.333333
007  小杨  80.666667

#### 展示students每个考试分数数据列的统计信息，包括个数、平均值、标准差、四分位数等

In [136]:
students[exam].describe()

        考试1  考试2  考试3
count     7    7    7
unique    6    6    6
top      79   89   92
freq      2    2    2