In [1]:
import pandas as pd

In [2]:
df_score = pd.read_excel('数据.xlsx',sheet_name='学生成绩表')
df_score

   学号  姓名  数学  英语  计算机
0   1  张三  85  90   88
1   2  李四  78  85   92
2   3  王五  90  88   85
3   4  赵六  60  70   65
4   5  孙七  80  82   78

In [ ]:
total_score = df_score[['数学','英语','计算机']].sum(axis=1)
df_score['总分'] = total_score
result = total_score.map(lambda x: "及格" if x >= 240 else "不及格")
df_score['及格情况'] = result
df_score

   学号  姓名  数学  英语  计算机   总分 及格情况
0   1  张三  85  90   88  263   及格
1   2  李四  78  85   92  255   及格
2   3  王五  90  88   85  263   及格
3   4  赵六  60  70   65  195  不及格
4   5  孙七  80  82   78  240   及格

In [32]:
def query_student_message(id):
    message = df_score.query(f'学号 == {id}')
    return message

In [33]:
print(query_student_message('1'))

   学号  姓名  数学  英语  计算机   总分 及格情况
0   1  张三  85  90   88  263   及格

In [34]:
df_sale = pd.read_excel('数据.xlsx',sheet_name='销售表')
df_sale

           日期  地区 产品名称  销售数量  销售金额
0  2024-01-01  北京  产品A    10   200
1  2024-01-01  上海  产品B    15   300
2  2024-01-02  北京  产品A    12   240
3  2024-01-02  广州  产品C     8   160
4  2024-01-03  上海  产品B    10   200

In [ ]:
pivot_sale = df_sale.pivot_table(
    values=['销售数量','销售金额'],  
    index='地区',      
    aggfunc='sum'      
)
print(pivot_sale)

    销售数量  销售金额
地区
上海    25   500
北京    22   440
广州     8   160