In [44]:
import pandas as pd

In [45]:
f1 = open('./运动员信息表.csv')
df = pd.read_csv(f1)
df

       姓名 性别 出生年份（年）  年龄（岁）  身高(cm)  体重(kg)      项目     省份
0     陈楠   女   1983年     35     197      90      篮球    山东省
1    白发全   男   1986年     32     175      64    铁人三项    云南省
2    陈晓佳   女   1988年     30     180      70      篮球    江苏省
3     陈倩   女   1987年     31     163      54  女子现代五项  江苏省
4    曹忠荣   男   1981年     37     180      73  男子现代五项    上海市
..    ... ..     ...    ...     ...     ...     ...    ...
174  赵芸蕾   女   1986年     32     173      62     羽毛球    湖北省
175   周琦   男   1996年     22     217      95      篮球   河南省
176  翟晓川   男   1993年     25     204     100      篮球   河北省
177  赵继伟   男   1995年     23     185      77      篮球    辽宁省
178  邹雨宸   男   1996年     22     208     108      篮球    辽宁省

[179 rows x 8 columns]

In [46]:
data_groupby_project = df.groupby('项目')
data_groupby_project.groups

{'举重': [18, 57, 77], '乒乓球': [17, 53, 76, 105, 131, 145, 156], '体操': [158], '击剑': [92, 104, 138], '女子100米栏': [115], '女子20公里竞走': [61, 63], '女子800米': [111], '女子三级跳远': [50], '女子中长跑': [31, 160], '女子撑杆跳': [91], '女子撑杆跳高': [66], '女子曲棍球': [11, 65, 70, 100, 167], '女子标枪': [49, 69, 71], '女子水球': [79, 98, 99, 149, 169], '女子现代五项': [3], '女子短跑': [22, 47, 51, 142], '女子铁饼': [19, 90], '女子链球': [125, 163], '女子马拉松': [144], '射击': [9, 13, 27, 44, 85, 118, 120, 153, 168], '射箭': [135], '帆船': [29, 126, 127, 133], '拳击': [94], '排球': [43, 87, 132, 140, 150, 166], '曲棍球': [74, 88, 119], '水球': [128, 164], '游泳': [24, 36, 37, 60, 62, 72, 82, 97, 107, 123, 129, 137, 154], '田径': [14, 21, 39, 40, 45, 46, 81, 83, 96, 108, 109, 113, 114, 130, 136, 139, 141, 146, 147, 157, 159, 173], '男子20公里竞走': [8, 117], '男子三级跳远': [6], '男子现代五项': [4], '男子跳高': [170], '皮划艇激流': [93], '皮划艇静水': [56, 67, 162], '篮球': [0, 2, 16, 23, 28, 35, 42, 48, 54, 73, 101, 102, 106, 116, 124, 155, 161, 175, 176, 177, 178], '网球': [84, 165], '羽毛球': [12, 15, 25, 58, 75, 80, 134, 143, 152, 171, 174], '自行车': [34, 64], '艺术体操': [95], '花剑': [52], '花样游泳': [7, 32, 59, 103, 112, 148], '赛艇': [41, 122, 151, 172], '跆拳道': [110], '跳水': [5, 10, 38, 68, 86, 89, 121], '蹦床': [20, 33, 55], '铁人三项': [1], '马术': [30], '高尔夫': [26, 78]}

# 统计篮球运动员的平均年龄、身高、体重

In [47]:

basketball_athletes = data_groupby_project.get_group('篮球')
basketball_athletes

        姓名 性别 出生年份（年）  年龄（岁）  身高(cm)  体重(kg)  项目        省份
0      陈楠   女   1983年     35     197      90  篮球       山东省
2     陈晓佳   女   1988年     30     180      70  篮球       江苏省
16   丁彦雨航   男   1993年     25     200      91  篮球  新疆维吾尔自治区
23     高颂   女   1992年     26     191      85  篮球    黑龙江省
28    郭艾伦   男   1993年     25     192      85  篮球       辽宁省
35    黄红枇   女   1989年     29     195      80  篮球   广西壮族自治区
42    黄思静   女   1996年     22     192      80  篮球       广东省
48    李慕豪   男   1992年     26     225     111  篮球      贵州贵阳
54    李珊珊   女   1987年     31     177      70  篮球     江苏省
73     露雯   女   1990年     28     191      78  篮球    内蒙古自治区
101   孙梦然   女   1992年     26     197      77  篮球       天津市
102   孙梦昕   女   1993年     25     190      77  篮球     山东省
106    睢冉   男   1992年     26     192      95  篮球       山西省
116    吴迪   女   1990年     28     186      72  篮球       天津市
124   王哲林   男   1994年     24     214     110  篮球      福建省
155   易建联   男   1987年     31     213     113  篮球       广东省
161    周鹏   男   1989年     29     206      90  篮球       辽宁省
175    周琦   男   1996年     22     217      95  篮球      河南省
176   翟晓川   男   1993年     25     204     100  篮球      河北省
177   赵继伟   男   1995年     23     185      77  篮球       辽宁省
178   邹雨宸   男   1996年     22     208     108  篮球       辽宁省

In [48]:
basketball_athletes_avg = basketball_athletes.agg({
    '年龄（岁）':'mean',
    '身高(cm)':'mean',
    '体重(kg)':'mean'
}).round(1)
basketball_athletes_avg.index = ['平均年龄（岁）','平均身高(cm)','平均体重(kg)']
basketball_athletes = basketball_athletes.assign(**basketball_athletes_avg.to_dict())
basketball_athletes

,姓名,性别,出生年份（年）,年龄（岁）,身高(cm),体重(kg),项目,省份,平均年龄（岁）,平均身高(cm),平均体重(kg)
0,陈楠,女,1983年,35,197,90,篮球,山东省,26.6,197.7,88.3
2,陈晓佳,女,1988年,30,180,70,篮球,江苏省,26.6,197.7,88.3
16,丁彦雨航,男,1993年,25,200,91,篮球,新疆维吾尔自治区,26.6,197.7,88.3
23,高颂,女,1992年,26,191,85,篮球,黑龙江省,26.6,197.7,88.3
28,郭艾伦,男,1993年,25,192,85,篮球,辽宁省,26.6,197.7,88.3
35,黄红枇,女,1989年,29,195,80,篮球,广西壮族自治区,26.6,197.7,88.3
42,黄思静,女,1996年,22,192,80,篮球,广东省,26.6,197.7,88.3
48,李慕豪,男,1992年,26,225,111,篮球,贵州贵阳,26.6,197.7,88.3
54,李珊珊,女,1987年,31,177,70,篮球,江苏省,26.6,197.7,88.3
73,露雯,女,1990年,28,191,78,篮球,内蒙古自治区,26.6,197.7,88.3
101,孙梦然,女,1992年,26,197,77,篮球,天津市,26.6,197.7,88.3
102,孙梦昕,女,1993年,25,190,77,篮球,山东省,26.6,197.7,88.3
106,睢冉,男,1992年,26,192,95,篮球,山西省,26.6,197.7,88.3
116,吴迪,女,1990年,28,186,72,篮球,天津市,26.6,197.7,88.3
124,王哲林,男,1994年,24,214,110,篮球,福建省,26.6,197.7,88.3
155,易建联,男,1987年,31,213,113,篮球,广东省,26.6,197.7,88.3
161,周鹏,男,1989年,29,206,90,篮球,辽宁省,26.6,197.7,88.3
175,周琦,男,1996年,22,217,95,篮球,河南省,26.6,197.7,88.3
176,翟晓川,男,1993年,25,204,100,篮球,河北省,26.6,197.7,88.3
177,赵继伟,男,1995年,23,185,77,篮球,辽宁省,26.6,197.7,88.3
178,邹雨宸,男,1996年,22,208,108,篮球,辽宁省,26.6,197.7,88.3

# 统计男运动员的年龄、身高、体重的极差值

In [49]:
def range_data(df):
    return df.max()-df.min()

In [50]:
basketball_athletes_groupby_sex = basketball_athletes.groupby('性别')
basketball_man_athletes = basketball_athletes_groupby_sex.get_group('男')
basketball_man_athletes

,姓名,性别,出生年份（年）,年龄（岁）,身高(cm),体重(kg),项目,省份,平均年龄（岁）,平均身高(cm),平均体重(kg)
16,丁彦雨航,男,1993年,25,200,91,篮球,新疆维吾尔自治区,26.6,197.7,88.3
28,郭艾伦,男,1993年,25,192,85,篮球,辽宁省,26.6,197.7,88.3
48,李慕豪,男,1992年,26,225,111,篮球,贵州贵阳,26.6,197.7,88.3
106,睢冉,男,1992年,26,192,95,篮球,山西省,26.6,197.7,88.3
124,王哲林,男,1994年,24,214,110,篮球,福建省,26.6,197.7,88.3
155,易建联,男,1987年,31,213,113,篮球,广东省,26.6,197.7,88.3
161,周鹏,男,1989年,29,206,90,篮球,辽宁省,26.6,197.7,88.3
175,周琦,男,1996年,22,217,95,篮球,河南省,26.6,197.7,88.3
176,翟晓川,男,1993年,25,204,100,篮球,河北省,26.6,197.7,88.3
177,赵继伟,男,1995年,23,185,77,篮球,辽宁省,26.6,197.7,88.3
178,邹雨宸,男,1996年,22,208,108,篮球,辽宁省,26.6,197.7,88.3

In [51]:
basketball_man_athletes_range = basketball_man_athletes.agg({
    '年龄（岁）':range_data,
    '身高(cm)':range_data,
    '体重(kg)':range_data
})
basketball_man_athletes_range.index = ['平均年龄（岁）','平均身高(cm)','平均体重(kg)']
basketball_man_athletes = basketball_man_athletes.assign(**basketball_man_athletes_range.to_dict())
basketball_man_athletes

,姓名,性别,出生年份（年）,年龄（岁）,身高(cm),体重(kg),项目,省份,平均年龄（岁）,平均身高(cm),平均体重(kg)
16,丁彦雨航,男,1993年,25,200,91,篮球,新疆维吾尔自治区,9,40,36
28,郭艾伦,男,1993年,25,192,85,篮球,辽宁省,9,40,36
48,李慕豪,男,1992年,26,225,111,篮球,贵州贵阳,9,40,36
106,睢冉,男,1992年,26,192,95,篮球,山西省,9,40,36
124,王哲林,男,1994年,24,214,110,篮球,福建省,9,40,36
155,易建联,男,1987年,31,213,113,篮球,广东省,9,40,36
161,周鹏,男,1989年,29,206,90,篮球,辽宁省,9,40,36
175,周琦,男,1996年,22,217,95,篮球,河南省,9,40,36
176,翟晓川,男,1993年,25,204,100,篮球,河北省,9,40,36
177,赵继伟,男,1995年,23,185,77,篮球,辽宁省,9,40,36
178,邹雨宸,男,1996年,22,208,108,篮球,辽宁省,9,40,36

# 统计篮球运动员的体质指数

In [52]:
def calculate_bmi(df):
    weight = df['体重(kg)']
    height = df['身高(cm)']
    bmi = weight/(height/100)**2
    return bmi

In [53]:
basketball_athletes['体质指数'] = (basketball_athletes.apply(calculate_bmi,axis=1)).round(1)
basketball_athletes

,姓名,性别,出生年份（年）,年龄（岁）,身高(cm),体重(kg),项目,省份,平均年龄（岁）,平均身高(cm),平均体重(kg),体质指数
0,陈楠,女,1983年,35,197,90,篮球,山东省,26.6,197.7,88.3,23.2
2,陈晓佳,女,1988年,30,180,70,篮球,江苏省,26.6,197.7,88.3,21.6
16,丁彦雨航,男,1993年,25,200,91,篮球,新疆维吾尔自治区,26.6,197.7,88.3,22.8
23,高颂,女,1992年,26,191,85,篮球,黑龙江省,26.6,197.7,88.3,23.3
28,郭艾伦,男,1993年,25,192,85,篮球,辽宁省,26.6,197.7,88.3,23.1
35,黄红枇,女,1989年,29,195,80,篮球,广西壮族自治区,26.6,197.7,88.3,21.0
42,黄思静,女,1996年,22,192,80,篮球,广东省,26.6,197.7,88.3,21.7
48,李慕豪,男,1992年,26,225,111,篮球,贵州贵阳,26.6,197.7,88.3,21.9
54,李珊珊,女,1987年,31,177,70,篮球,江苏省,26.6,197.7,88.3,22.3
73,露雯,女,1990年,28,191,78,篮球,内蒙古自治区,26.6,197.7,88.3,21.4
101,孙梦然,女,1992年,26,197,77,篮球,天津市,26.6,197.7,88.3,19.8
102,孙梦昕,女,1993年,25,190,77,篮球,山东省,26.6,197.7,88.3,21.3
106,睢冉,男,1992年,26,192,95,篮球,山西省,26.6,197.7,88.3,25.8
116,吴迪,女,1990年,28,186,72,篮球,天津市,26.6,197.7,88.3,20.8
124,王哲林,男,1994年,24,214,110,篮球,福建省,26.6,197.7,88.3,24.0
155,易建联,男,1987年,31,213,113,篮球,广东省,26.6,197.7,88.3,24.9
161,周鹏,男,1989年,29,206,90,篮球,辽宁省,26.6,197.7,88.3,21.2
175,周琦,男,1996年,22,217,95,篮球,河南省,26.6,197.7,88.3,20.2
176,翟晓川,男,1993年,25,204,100,篮球,河北省,26.6,197.7,88.3,24.0
177,赵继伟,男,1995年,23,185,77,篮球,辽宁省,26.6,197.7,88.3,22.5
178,邹雨宸,男,1996年,22,208,108,篮球,辽宁省,26.6,197.7,88.3,25.0