In [57]:
import pandas as pd

In [58]:
f1 = open('./运动员信息表.csv')
df = pd.read_csv(f1)
df

       姓名 性别 出生年份（年）  年龄（岁）  身高(cm)  体重(kg)      项目     省份
0     陈楠   女   1983年     35     197      90      篮球    山东省
1    白发全   男   1986年     32     175      64    铁人三项    云南省
2    陈晓佳   女   1988年     30     180      70      篮球    江苏省
3     陈倩   女   1987年     31     163      54  女子现代五项  江苏省
4    曹忠荣   男   1981年     37     180      73  男子现代五项    上海市
..    ... ..     ...    ...     ...     ...     ...    ...
174  赵芸蕾   女   1986年     32     173      62     羽毛球    湖北省
175   周琦   男   1996年     22     217      95      篮球   河南省
176  翟晓川   男   1993年     25     204     100      篮球   河北省
177  赵继伟   男   1995年     23     185      77      篮球    辽宁省
178  邹雨宸   男   1996年     22     208     108      篮球    辽宁省

[179 rows x 8 columns]

In [ ]:
def outer(df_basketball):
    '''
    计算bmi
    '''
    weight = df_basketball['体重(kg)']
    height = df_basketball['身高(cm)']
    sum_bmi = weight / (height/100)**2
    return sum_bmi

In [ ]:
def range_data_group(arr):
    '''
    计算极差
    '''
    return arr.max()-arr.min()

In [ ]:
data_groupby_project = df.groupby('项目')
for data in data_groupby_project:
    print(data)

('举重',       姓名 性别 出生年份（年）  年龄（岁）  身高(cm)  体重(kg)  项目     省份
18   邓薇   女   1993年     25     158      60  举重    福建省
57  龙清泉   男   1990年     28     156      56  举重  湖南省
77  吕小军   男   1984年     34     172      77  举重    湖北省)
('乒乓球',        姓名 性别 出生年份（年）  年龄（岁）  身高(cm)  体重(kg)   项目      省份
17    丁宁   女   1990年     28     170      63  乒乓球  黑龙江省
53   李晓霞   女   1988年     30     174      64  乒乓球     辽宁省
76    马龙   男   1988年     30     175      72  乒乓球     辽宁省
105   王宇   男   1991年     27     188      75  乒乓球   山东省
131   许昕   男   1990年     28     180      67  乒乓球     上海市
145   杨洋   男   1991年     27     183      75  乒乓球   山东省
156  张继科   男   1988年     30     181      70  乒乓球   山东省  )
('体操',        姓名 性别 出生年份（年）  年龄（岁）  身高(cm)  体重(kg)  项目   省份
158  张成龙   男   1989年     29     173      65  体操  山东省)
('击剑',        姓名 性别 出生年份（年）  年龄（岁）  身高(cm)  体重(kg)  项目     省份
92    沈晨   女   1990年     28     171      60  击剑  江苏省
104  孙玉洁   女   1992年     26     185      72  击剑    辽宁省
138  许安琪   女   1992年     26     183      75  击剑  江苏省  )
('女子100米栏',        姓名 性别 出生年份（年）  年龄（岁）  身高(cm)  体重(kg)       项目   省份
115  吴水娇   女   1991年     27     176      65  女子100米栏  广东省)
('女子20公里竞走',       姓名 性别 出生年份（年）  年龄（岁）  身高(cm)  体重(kg)        项目   省份
61   刘虹   女   1987年     31     161      48  女子20公里竞走  江西省
63  吕秀芝   女   1993年     25     156      42  女子20公里竞走  安徽省)
('女子800米',        姓名 性别 出生年份（年）  年龄（岁）  身高(cm)  体重(kg)      项目   省份
111  王春雨   女   1995年     23     176      43  女子800米  安徽省)
('女子三级跳远',       姓名 性别 出生年份（年）  年龄（岁）  身高(cm)  体重(kg)      项目   省份
50  李小红   女   1995年     23     175      56  女子三级跳远  福建省)
('女子中长跑',        姓名 性别 出生年份（年）  年龄（岁）  身高(cm)  体重(kg)     项目     省份
31   华绍青   女   1994年     24     172      54  女子中长跑  河北省
160  张新艳   女   1994年     24     164      48  女子中长跑    甘肃省)
('女子撑杆跳',       姓名 性别 出生年份（年）  年龄（岁）  身高(cm)  体重(kg)     项目   省份
91  任梦茜   女   1993年     25     178      65  女子撑杆跳  浙江省)
('女子撑杆跳高',         姓名 性别 出生年份（年）  年龄（岁）  身高(cm)  体重(kg)      项目     省份
66  李玲[2]   女   1989年     29     185      63  女子撑杆跳高  山东省  )
('女子曲棍球',        姓名 性别 出生年份（年）  年龄（岁）  身高(cm)  体重(kg)     项目   省份
11   德娇娇   女   1990年     28     168      56  女子曲棍球  天津市
65   李冬晓   女   1987年     31     175      60  女子曲棍球  辽宁省
70   李红侠   女   1986年     32     169      62  女子曲棍球  辽宁省
100  宋清龄   女   1986年     32     174      71  女子曲棍球  辽宁省
167  赵玉雕   女   1989年     29     174      70  女子曲棍球  辽宁省)
('女子标枪',       姓名 性别 出生年份（年）  年龄（岁）  身高(cm)  体重(kg)    项目     省份
49  刘诗颖   女   1993年     25     178      78  女子标枪  山东省
69  吕会会   女   1989年     29     171      68  女子标枪  河南省
71  李玲蔚   女   1989年     29     175      68  女子标枪  山东省  )
('女子水球',        姓名 性别 出生年份（年）  年龄（岁）  身高(cm)  体重(kg)    项目       省份
79   马欢欢   女   1990年     28     178      73  女子水球  广西壮族自治区
98   孙雅婷   女   1988年     30     180      78  女子水球      天津市
99   宋冬伦   女   1991年     27     178      82  女子水球      北京市
149   杨珺   女   1988年     30     180      69  女子水球      北京市
169  张薇薇   女   1990年     28     183      64  女子水球      辽宁省)
('女子现代五项',     姓名 性别 出生年份（年）  年龄（岁）  身高(cm)  体重(kg)      项目     省份
3  陈倩   女   1987年     31     163      54  女子现代五项  江苏省  )
('女子短跑',        姓名 性别 出生年份（年）  年龄（岁）  身高(cm)  体重(kg)    项目      省份
22   葛曼棋   女   1997年     21     160      48  女子短跑     福建省
47   孔令微   女   1995年     23     165      55  女子短跑  黑龙江省
51   梁小静   女   1997年     21     156      45  女子短跑     广东省
142  袁琦琦   女   1995年     23     165      50  女子短跑   江苏省  )
('女子铁饼',       姓名 性别 出生年份（年）  年龄（岁）  身高(cm)  体重(kg)    项目     省份
19   冯彬   女   1994年     24     184      95  女子铁饼  山东省
90  苏欣悦   女   1991年     27     178      95  女子铁饼  河北省  )
('女子链球',        姓名 性别 出生年份（年）  年龄（岁）  身高(cm)  体重(kg)    项目   省份
125   王峥   女   1987年     31     174      87  女子链球  陕西省
163  张文秀   女   1986年     32     182     113  女子链球  辽宁省)
('女子马拉松',       姓名 性别 出生年份（年）  年龄（岁）  身高(cm)  体重(kg)     项目     省份
144  岳超   女   1991年     27     165      55  女子马拉松  江苏省  )
('射击',        姓名 性别 出生年份（年）  年龄（岁）  身高(cm)  体重(kg)  项目     省份
9     陈颖   女   1977年     41     164      75  射击    北京市
13    杜丽   女   1982年     36     170      55  射击  山东省
27   郭文珺   女   1984年     34     168      65  射击    陕西省
44   胡斌渊   男   1977年     41     180      67  射击    上海市
85    庞伟   男   1986年     32     179      80  射击  河北省
118   魏宁   女   1982年     36     166      60  射击  山东省
120  王智伟   男   1988年     30     178      75  射击    山西省
153  易思玲   女   1989年     29     165      51  射击  湖南省
168  朱启南   男   1984年     34     182      67  射击    浙江省)
('射箭',       姓名 性别 出生年份（年）  年龄（岁）  身高(cm)  体重(kg)  项目   省份
135  邢宇   男   1991年     27     188      77  射箭  北京市)
('帆船',        姓名 性别 出生年份（年）  年龄（岁）  身高(cm)  体重(kg)  项目   省份
29    宫磊   男   1983年     35     185      88  帆船  山东省
126  王爱忱   男   1985年     33     185      70  帆船  辽宁省
127  王晓丽   女   1982年     36     169      70  帆船  山东省
133  徐莉佳   女   1987年     31     176      60  帆船  上海市)
('拳击',       姓名 性别 出生年份（年）  年龄（岁）  身高(cm)  体重(kg)  项目   省份
94  任灿灿   女   1988年     30     167      51  拳击  山东省)
('排球',        姓名 性别 出生年份（年）  年龄（岁）  身高(cm)  体重(kg)  项目     省份
43   惠若琪   女   1991年     27     191      77  排球    辽宁省
87    彭林   女   1995年     23     184      72  排球  湖南省
132  魏秋月   女   1988年     30     183      75  排球    天津市
140  徐云丽   女   1987年     31     197      86  排球   福建省
150   颜妮   女   1989年     29     192      72  排球    辽宁省
166  赵子涵   女   1993年     25     173      63  排球    上海市)
('曲棍球',        姓名 性别 出生年份（年）  年龄（岁）  身高(cm)  体重(kg)   项目     省份
74   梁美玉   女   1994年     24     166      65  曲棍球    广东省
88    彭杨   女   1992年     26     163      59  曲棍球  四川省
119  王梦雨   女   1992年     26     170      70  曲棍球  江苏省  )
('水球',        姓名 性别 出生年份（年）  年龄（岁）  身高(cm)  体重(kg)  项目   省份
128  王歆艳   女   1991年     27     181      73  水球  上海市
164   张潀   女   1990年     28     176      65  水球  天津市)
('游泳',        姓名 性别 出生年份（年）  年龄（岁）  身高(cm)  体重(kg)  项目     省份
24   傅园慧   女   1996年     22     177      63  游泳    浙江省
36   何健彬   男   1993年     25     188      79  游泳    广东省
37    顾笑   女   1993年     25     174      60  游泳  江苏省
60   林永庆   男   1992年     26     190      80  游泳    辽宁省
62    李响   男   1993年     25     192      86  游泳    天津市
72    陆滢   女   1989年     29     175      62  游泳    上海市
82   宁泽涛   男   1993年     25     191      77  游泳  河南省
97    孙杨   男   1991年     27     198      89  游泳    浙江省
107   唐奕   女   1993年     25     177      70  游泳    上海市
123   汪顺   男   1994年     24     192      74  游泳    浙江省
129  王施佳   女   1993年     25     173      62  游泳    辽宁省
137   辛鑫   女   1996年     22     175      58  游泳  山东省
154  叶诗文   女   1996年     22     172      64  游泳    浙江省)
('田径',         姓名 性别 出生年份（年）  年龄（岁）  身高(cm)  体重(kg)  项目      省份
14    多布杰   男   1994年     24     170      55  田径   西藏自治区
21    董国建   男   1987年     31     172      60  田径   云南省
39    高兴龙   男   1994年     24     181      70  田径  黑龙江省
40    韩玉成   男   1978年     40     175      63  田径     辽宁省
45    黄常洲   男   1994年     24     186      73  田径   四川省
46    黄博凯   男   1996年     22     192      78  田径     广东省
81    莫有雪   男   1988年     30     179      65  田径     广东省
83   切阳什姐   女   1990年     28     159      47  田径     青海省
96    苏炳添   男   1989年     29     172      65  田径     广东省
108   唐功臣   男   1989年     29     180      68  田径   河北省
109   汤星强   男   1995年     23     170      65  田径     福建省
113   王凯华   男   1994年     24     175      55  田径     广东省
114   王振东   男   1991年     27     175      62  田径   江苏省
130   徐晓龙   男   1992年     26     188      70  田径     重庆市
136   谢震业   男   1993年     25     183      76  田径     浙江省
139   王嘉男   男   1988年     30     185      70  田径     辽宁省
141    于伟   男   1987年     31     180      62  田径   山东省
146   谢文骏   男   1990年     28     190      85  田径     上海市
147   薛长锐   男   1991年     27     188      75  田径   山东省
157   朱仁学   男   1991年     27     181      70  田径   云南省
159    张航   男   1991年     27     180      70  田径   云南省
173   张培萌   男   1987年     31     186      86  田径     北京市)
('男子20公里竞走',       姓名 性别 出生年份（年）  年龄（岁）  身高(cm)  体重(kg)        项目      省份
8    陈定   男   1992年     26     177      61  男子20公里竞走   云南省
117  王镇   男   1991年     27     177      63  男子20公里竞走  黑龙江省  )
('男子三级跳远',     姓名 性别 出生年份（年）  年龄（岁）  身高(cm)  体重(kg)      项目     省份
6  曹硕   男   1991年     27     180      76  男子三级跳远  河北省  )
('男子现代五项',      姓名 性别 出生年份（年）  年龄（岁）  身高(cm)  体重(kg)      项目   省份
4  曹忠荣   男   1981年     37     180      73  男子现代五项  上海市)
('男子跳高',        姓名 性别 出生年份（年）  年龄（岁）  身高(cm)  体重(kg)    项目     省份
170  张国伟   男   1991年     27     200      77  男子跳高  山东省  )
('皮划艇激流',       姓名 性别 出生年份（年）  年龄（岁）  身高(cm)  体重(kg)     项目     省份
93  任文君   女   1992年     26     175      67  皮划艇激流  山东省  )
('皮划艇静水',        姓名 性别 出生年份（年）  年龄（岁）  身高(cm)  体重(kg)     项目     省份
56    李强   男   1989年     29     185      83  皮划艇静水    辽宁省
67   刘海萍   女   1988年     30     174      70  皮划艇静水    山东省
162   周玉   女   1989年     29     174      68  皮划艇静水  湖南省  )
('篮球',         姓名 性别 出生年份（年）  年龄（岁）  身高(cm)  体重(kg)  项目        省份
0      陈楠   女   1983年     35     197      90  篮球       山东省
2     陈晓佳   女   1988年     30     180      70  篮球       江苏省
16   丁彦雨航   男   1993年     25     200      91  篮球  新疆维吾尔自治区
23     高颂   女   1992年     26     191      85  篮球    黑龙江省
28    郭艾伦   男   1993年     25     192      85  篮球       辽宁省
35    黄红枇   女   1989年     29     195      80  篮球   广西壮族自治区
42    黄思静   女   1996年     22     192      80  篮球       广东省
48    李慕豪   男   1992年     26     225     111  篮球      贵州贵阳
54    李珊珊   女   1987年     31     177      70  篮球     江苏省
73     露雯   女   1990年     28     191      78  篮球    内蒙古自治区
101   孙梦然   女   1992年     26     197      77  篮球       天津市
102   孙梦昕   女   1993年     25     190      77  篮球     山东省
106    睢冉   男   1992年     26     192      95  篮球       山西省
116    吴迪   女   1990年     28     186      72  篮球       天津市
124   王哲林   男   1994年     24     214     110  篮球      福建省
155   易建联   男   1987年     31     213     113  篮球       广东省
161    周鹏   男   1989年     29     206      90  篮球       辽宁省
175    周琦   男   1996年     22     217      95  篮球      河南省
176   翟晓川   男   1993年     25     204     100  篮球      河北省
177   赵继伟   男   1995年     23     185      77  篮球       辽宁省
178   邹雨宸   男   1996年     22     208     108  篮球       辽宁省)
('网球',       姓名 性别 出生年份（年）  年龄（岁）  身高(cm)  体重(kg)  项目   省份
84   彭帅   女   1986年     32     173      65  网球  天津市
165  张帅   女   1989年     29     177      65  网球  天津市)
('羽毛球',        姓名 性别 出生年份（年）  年龄（岁）  身高(cm)  体重(kg)   项目     省份
12    谌龙   男   1989年     29     188      78  羽毛球    福建省
15    柴飚   男   1990年     28     183      70  羽毛球  湖南省
25   傅海峰   男   1984年     34     181      78  羽毛球    广东省
58    林丹   男   1983年     35     177      70  羽毛球    福建省
75   李雪芮   女   1991年     27     173      65  羽毛球    重庆市
80    马晋   女   1988年     30     167      60  羽毛球  江苏省
134  王仪涵   女   1988年     30     178      65  羽毛球    上海市
143   徐晨   男   1984年     34     186      80  羽毛球  江苏省
152   于洋   女   1986年     32     166      56  羽毛球    辽宁省
171   张楠   男   1990年     28     183      75  羽毛球    北京市
174  赵芸蕾   女   1986年     32     173      62  羽毛球    湖北省)
('自行车',       姓名 性别 出生年份（年）  年龄（岁）  身高(cm)  体重(kg)   项目    省份
34  宫金杰   女   1986年     32     168      67  自行车   吉林省
64  林俊红   女   1990年     28     163      61  自行车  黑龙江省)
('艺术体操',       姓名 性别 出生年份（年）  年龄（岁）  身高(cm)  体重(kg)    项目     省份
95  舒思瑶   女   1992年     26     172      49  艺术体操  四川省  )
('花剑',      姓名 性别 出生年份（年）  年龄（岁）  身高(cm)  体重(kg)  项目   省份
52  雷声   男   1984年     34     193      75  花剑  天津市)
('花样游泳',        姓名 性别 出生年份（年）  年龄（岁）  身高(cm)  体重(kg)    项目     省份
7     曾珍   女   1993年     25     170      61  花样游泳  四川省
32   黄雪辰   女   1990年     28     175      62  花样游泳    上海市
59   梁馨枰   女   1994年     24     171      60  花样游泳  江苏省
103  孙文雁   女   1989年     29     170      58  花样游泳  湖南省
112  汤梦妮   女   1994年     24     169      59  花样游泳    上海市
148  尹成昕   女   1995年     23     168      58  花样游泳    湖北省)
('赛艇',        姓名 性别 出生年份（年）  年龄（岁）  身高(cm)  体重(kg)  项目   省份
41   黄文仪   女   1991年     27     178      63  赛艇  广东省
122  王铁鑫   男   1989年     29     188      75  赛艇  浙江省
151  余成刚   男   1984年     34     181      70  赛艇  四川省
172  朱韦伟   女   1990年     28     180      72  赛艇  江苏省)
('跆拳道',        姓名 性别 出生年份（年）  年龄（岁）  身高(cm)  体重(kg)   项目   省份
110  吴静钰   女   1987年     31     167      49  跆拳道  江西省)
('跳水',        姓名 性别 出生年份（年）  年龄（岁）  身高(cm)  体重(kg)  项目       省份
5     曹缘   男   1995年     23     160      42  跳水      北京市
10   陈若琳   女   1992年     26     158      47  跳水      江苏省
38    何姿   女   1990年     28     159      51  跳水  广西壮族自治区
68    林跃   男   1991年     27     157      46  跳水      北京市
86    邱波   男   1993年     25     162      59  跳水      四川省
89    秦凯   男   1986年     32     170      65  跳水      陕西省
121  吴敏霞   女   1985年     33     167      53  跳水      上海市)
('蹦床',       姓名 性别 出生年份（年）  年龄（岁）  身高(cm)  体重(kg)  项目     省份
20   董栋   男   1989年     29     168      60  蹦床  河南省
33  何雯娜   女   1989年     29     160      48  蹦床    福建省
55   李丹   女   1989年     29     155      48  蹦床    广东省)
('铁人三项',      姓名 性别 出生年份（年）  年龄（岁）  身高(cm)  体重(kg)    项目   省份
1  白发全   男   1986年     32     175      64  铁人三项  云南省)
('马术',      姓名 性别 出生年份（年）  年龄（岁）  身高(cm)  体重(kg)  项目   省份
30  华天   男   1989年     29     187      70  马术  北京市)
('高尔夫',       姓名 性别 出生年份（年）  年龄（岁）  身高(cm)  体重(kg)   项目     省份
26  冯珊珊   女   1989年     29     173      68  高尔夫    广东省
78  李昊桐   男   1995年     23     183      75  高尔夫  湖南省  )

In [62]:
# 统计篮球运动员的平均年龄、身高、体重
df_basketball = dict([x for x in data_group])['篮球']
print(df_basketball)
avg_data = df_basketball[['年龄（岁）','身高(cm)','体重(kg)']].mean().round(0)
# print(f'运动员的平均年龄为:{avg_age}')
avg_data.index = ['平均年龄（岁）','平均身高(cm)','平均体重(kg)']
avg_data

        姓名 性别 出生年份（年）  年龄（岁）  身高(cm)  体重(kg)  项目        省份
0      陈楠   女   1983年     35     197      90  篮球       山东省
2     陈晓佳   女   1988年     30     180      70  篮球       江苏省
16   丁彦雨航   男   1993年     25     200      91  篮球  新疆维吾尔自治区
23     高颂   女   1992年     26     191      85  篮球    黑龙江省
28    郭艾伦   男   1993年     25     192      85  篮球       辽宁省
35    黄红枇   女   1989年     29     195      80  篮球   广西壮族自治区
42    黄思静   女   1996年     22     192      80  篮球       广东省
48    李慕豪   男   1992年     26     225     111  篮球      贵州贵阳
54    李珊珊   女   1987年     31     177      70  篮球     江苏省
73     露雯   女   1990年     28     191      78  篮球    内蒙古自治区
101   孙梦然   女   1992年     26     197      77  篮球       天津市
102   孙梦昕   女   1993年     25     190      77  篮球     山东省
106    睢冉   男   1992年     26     192      95  篮球       山西省
116    吴迪   女   1990年     28     186      72  篮球       天津市
124   王哲林   男   1994年     24     214     110  篮球      福建省
155   易建联   男   1987年     31     213     113  篮球       广东省
161    周鹏   男   1989年     29     206      90  篮球       辽宁省
175    周琦   男   1996年     22     217      95  篮球      河南省
176   翟晓川   男   1993年     25     204     100  篮球      河北省
177   赵继伟   男   1995年     23     185      77  篮球       辽宁省
178   邹雨宸   男   1996年     22     208     108  篮球       辽宁省

平均年龄（岁）      27.0
平均身高(cm)    198.0
平均体重(kg)     88.0
dtype: float64

In [ ]:
# 统计篮球运动员的平均年龄、身高、体重
basketball_athletes = data_groupby_project.get_group('篮球')

In [64]:
groupby_sex = df_basketball.groupby('性别')
for sex in groupby_sex:
    print(sex)

('女',        姓名 性别 出生年份（年）  年龄（岁）  身高(cm)  体重(kg)  项目       省份
0     陈楠   女   1983年     35     197      90  篮球      山东省
2    陈晓佳   女   1988年     30     180      70  篮球      江苏省
23    高颂   女   1992年     26     191      85  篮球   黑龙江省
35   黄红枇   女   1989年     29     195      80  篮球  广西壮族自治区
42   黄思静   女   1996年     22     192      80  篮球      广东省
54   李珊珊   女   1987年     31     177      70  篮球    江苏省
73    露雯   女   1990年     28     191      78  篮球   内蒙古自治区
101  孙梦然   女   1992年     26     197      77  篮球      天津市
102  孙梦昕   女   1993年     25     190      77  篮球    山东省
116   吴迪   女   1990年     28     186      72  篮球      天津市)
('男',         姓名 性别 出生年份（年）  年龄（岁）  身高(cm)  体重(kg)  项目        省份
16   丁彦雨航   男   1993年     25     200      91  篮球  新疆维吾尔自治区
28    郭艾伦   男   1993年     25     192      85  篮球       辽宁省
48    李慕豪   男   1992年     26     225     111  篮球      贵州贵阳
106    睢冉   男   1992年     26     192      95  篮球       山西省
124   王哲林   男   1994年     24     214     110  篮球      福建省
155   易建联   男   1987年     31     213     113  篮球       广东省
161    周鹏   男   1989年     29     206      90  篮球       辽宁省
175    周琦   男   1996年     22     217      95  篮球      河南省
176   翟晓川   男   1993年     25     204     100  篮球      河北省
177   赵继伟   男   1995年     23     185      77  篮球       辽宁省
178   邹雨宸   男   1996年     22     208     108  篮球       辽宁省)

In [65]:
# 统计男运动员的年龄、身高、体重的极差值
man_basketball = groupby_sex.get_group('男')
print(man_basketball)
# max_min = range_data_group(man_basketball['体重(kg)'])
new = man_basketball.agg({'年龄（岁）':range_data_group,
                    '身高(cm)':range_data_group,                           
                    '体重(kg)':range_data_group
})
new

        姓名 性别 出生年份（年）  年龄（岁）  身高(cm)  体重(kg)  项目        省份
16   丁彦雨航   男   1993年     25     200      91  篮球  新疆维吾尔自治区
28    郭艾伦   男   1993年     25     192      85  篮球       辽宁省
48    李慕豪   男   1992年     26     225     111  篮球      贵州贵阳
106    睢冉   男   1992年     26     192      95  篮球       山西省
124   王哲林   男   1994年     24     214     110  篮球      福建省
155   易建联   男   1987年     31     213     113  篮球       广东省
161    周鹏   男   1989年     29     206      90  篮球       辽宁省
175    周琦   男   1996年     22     217      95  篮球      河南省
176   翟晓川   男   1993年     25     204     100  篮球      河北省
177   赵继伟   男   1995年     23     185      77  篮球       辽宁省
178   邹雨宸   男   1996年     22     208     108  篮球       辽宁省

年龄（岁）      9
身高(cm)    40
体重(kg)    36
dtype: int64

In [66]:
df_basketball['体质指数'] = 0
df_basketball

        姓名 性别 出生年份（年）  年龄（岁）  身高(cm)  体重(kg)  项目        省份  体质指数
0      陈楠   女   1983年     35     197      90  篮球       山东省     0
2     陈晓佳   女   1988年     30     180      70  篮球       江苏省     0
16   丁彦雨航   男   1993年     25     200      91  篮球  新疆维吾尔自治区     0
23     高颂   女   1992年     26     191      85  篮球    黑龙江省       0
28    郭艾伦   男   1993年     25     192      85  篮球       辽宁省     0
35    黄红枇   女   1989年     29     195      80  篮球   广西壮族自治区     0
42    黄思静   女   1996年     22     192      80  篮球       广东省     0
48    李慕豪   男   1992年     26     225     111  篮球      贵州贵阳     0
54    李珊珊   女   1987年     31     177      70  篮球     江苏省       0
73     露雯   女   1990年     28     191      78  篮球    内蒙古自治区     0
101   孙梦然   女   1992年     26     197      77  篮球       天津市     0
102   孙梦昕   女   1993年     25     190      77  篮球     山东省       0
106    睢冉   男   1992年     26     192      95  篮球       山西省     0
116    吴迪   女   1990年     28     186      72  篮球       天津市     0
124   王哲林   男   1994年     24     214     110  篮球      福建省      0
155   易建联   男   1987年     31     213     113  篮球       广东省     0
161    周鹏   男   1989年     29     206      90  篮球       辽宁省     0
175    周琦   男   1996年     22     217      95  篮球      河南省      0
176   翟晓川   男   1993年     25     204     100  篮球      河北省      0
177   赵继伟   男   1995年     23     185      77  篮球       辽宁省     0
178   邹雨宸   男   1996年     22     208     108  篮球       辽宁省     0

In [80]:
# 统计篮球运动员的体质指数
bim = df_basketball['体质指数']
df_basketball['体质指数'] = df_basketball.apply(outer,axis=1)                                                             
df_basketball

        姓名 性别 出生年份（年）  年龄（岁）  身高(cm)  体重(kg)  项目        省份       体质指数
0      陈楠   女   1983年     35     197      90  篮球       山东省  23.190497
2     陈晓佳   女   1988年     30     180      70  篮球       江苏省  21.604938
16   丁彦雨航   男   1993年     25     200      91  篮球  新疆维吾尔自治区  22.750000
23     高颂   女   1992年     26     191      85  篮球    黑龙江省    23.299800
28    郭艾伦   男   1993年     25     192      85  篮球       辽宁省  23.057726
35    黄红枇   女   1989年     29     195      80  篮球   广西壮族自治区  21.038790
42    黄思静   女   1996年     22     192      80  篮球       广东省  21.701389
48    李慕豪   男   1992年     26     225     111  篮球      贵州贵阳  21.925926
54    李珊珊   女   1987年     31     177      70  篮球     江苏省    22.343516
73     露雯   女   1990年     28     191      78  篮球    内蒙古自治区  21.380993
101   孙梦然   女   1992年     26     197      77  篮球       天津市  19.840759
102   孙梦昕   女   1993年     25     190      77  篮球     山东省    21.329640
106    睢冉   男   1992年     26     192      95  篮球       山西省  25.770399
116    吴迪   女   1990年     28     186      72  篮球       天津市  20.811655
124   王哲林   男   1994年     24     214     110  篮球      福建省   24.019565
155   易建联   男   1987年     31     213     113  篮球       广东省  24.906875
161    周鹏   男   1989年     29     206      90  篮球       辽宁省  21.208408
175    周琦   男   1996年     22     217      95  篮球      河南省   20.174563
176   翟晓川   男   1993年     25     204     100  篮球      河北省   24.029220
177   赵继伟   男   1995年     23     185      77  篮球       辽宁省  22.498174
178   邹雨宸   男   1996年     22     208     108  篮球       辽宁省  24.963018